# エラーがある場合にビルド・デプロイをしてしまうとページが正常に見れなくなるので、エラーがあるかどうかを事前にチェックするためのワークフロー
name: Lint Check for Root and src

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"

jobs:
  lint-check-root:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
